WIP: Extend UID regex with '. ' and use it in SDocNode
strictdoc-project/strictdoc pull request #1902
Opened 2024-06-29 12:15 UTC by haxtibal

This fixes two things:
- The UID regex is now used in SDocNode to make UID character validation consistent with UIDs from DOCUMENT, SECTION, LINK, ANCHOR.
- The UID regex is extended so that it allows to use dots and whitespaces inside UIDs (but not as 1st character).

There are multiple approaches how one could fix the issues. This one is the least invasive and most backwards compatible one.
- It keeps UIDs allowed at arbitrary field positions in custom grammars for backwards compatibility.
- It continues to model a UID as python class SDocNodeField. So no code has to be changed at all (besides TextX grammar).

This sdoc works now:
```
[DOCUMENT]
TITLE: Link to UID with whitespace and dot

[REQUIREMENT]
UID: ISO whatever 47.11
STATEMENT: Foo

[TEXT]
STATEMENT: >>>
See [LINK: ISO whatever 47.11]
<<<

Fixes #1897.

2024-06-29 12:20 UTC, haxtibal commented
I'll have to look at failed tests and implement new ones, therefore WIP. You can already start to comment the approach anyways.

2024-06-30 12:32 UTC, stanislaw requested changes
This is a very good change. I only left one comment.

The only consideration I have about this is whether the UID validation should be handled at a grammar level or later during `validate_requirement_field`.

The advantage of your approach at the grammar time is that the UID validation happens early, and we get a feedback right away. Also, the UID messages are more specific now which is confirmed by the nice change that you had to make to the unit tests.

Now to the advantages of the validation in SDocValidator when the object graph is already parsed. Over time, I had to optimize several textX/Arpeggio performance issues related to how the StrictDoc grammar was written, see here for a major example: https://github.com/textX/textX/pull/406/files. The lesson learned was that textX/Arpeggio are reasonably fast but it is always nice to find a way to do as less work in the SDoc textX grammar as possible.

With this particular change, Arpeggio will have to jump over UID/non-UID branches when parsing every node field. This should not have much performance overhead but logically, this kind of extra branching is still introduced. If we did this with the `validate_requirement_field()`, we could create a dictionary:

```py
FIELD_VALIDATORS = {
    "UID": validate_uid,
    ...
}
```

and then the `validate_requirement_field` would simply call:


```py
field_validation = FIELD_VALIDATORS.get(field_name, None)
if field_validation is not None:
    field_validation(node)
```

This FIELD_VALIDATORS will come to play anyway when the https://github.com/strictdoc-project/strictdoc/issues/1229 is worked on, so the number of validations implemented in `validate_requirement_field` will grow.

Your change as-is is fine at the moment but eventually we will probably have to move it to happen in `validate_requirement_field`. Also, the validations of the MID as a unique field should happen in Python, not through the SDoc textX grammar restrictions. 

Having this all written, I think it is best if we move the UID regex validation to the SDocValidator right away, introducing the `FIELD_VALIDATORS` and field-specific validation functions. The half of your patch will have to be removed, and a unit test catching a validation for invalid UIDs will have to be written.

Let me know if you see any disadvantages of not doing the validation in `validate_requirement_field`.

2024-06-30 12:32 UTC, stanislaw commented on strictdoc/backend/sdoc/grammar/grammar.py
> +    field_name = 'UID' ': ' parts=/{REGEX_UID}/ '\n'
```suggestion
    field_name = 'UID' ': ' parts+=/{REGEX_UID}/ '\n'
```

2024-06-30 12:53 UTC, stanislaw approved these changes

2024-06-30 12:54 UTC, stanislaw commented on strictdoc/backend/sdoc/grammar/grammar.py
> +    field_name = 'UID' ': ' parts=/{REGEX_UID}/ '\n'
I applied it myself as a code suggestion.

2024-06-30 12:54 UTC, merged

2024-06-30 21:13 UTC, haxtibal commented
Thanks for sharing this very interesting insights.

> With this particular change, Arpeggio will have to jump over UID/non-UID branches when parsing every node field. This should not have much performance overhead but logically, this kind of extra branching is still introduced.

The UID branch is less likely than the generic field branch. UID should have been checked 2nd. Doesn't matter much if we remove the branch soon anyway.

> ```python
> FIELD_VALIDATORS = {
>     "UID": validate_uid,
>     ...
> }
> ```
> 
> and then the `validate_requirement_field` would simply call:
> 
> ```python
> field_validation = FIELD_VALIDATORS.get(field_name, None)
> if field_validation is not None:
>     field_validation(node)
> ```

Looks good. We'll need a function similar to `validate_requirement_field` to check UIDs of DocumentConfig and SDocSection the same way.

> Having this all written, I think it is best if we move the UID regex validation to the SDocValidator right away, introducing the `FIELD_VALIDATORS` and field-specific validation functions. The half of your patch will have to be removed, and a unit test catching a validation for invalid UIDs will have to be written.

This is well reasoned. I'm glad you merged the PR anyway as it allows me to do some immediate show cases.
 
> Let me know if you see any disadvantages of not doing the validation in `validate_requirement_field`.

The only thing I can think of as disadvantage is that 3rd parties (e.g. language server, syntax highlighter, linter, ...) have a harder job reimplementing sdoc validation. They get for free what's written as TextX. The rules written in Python are harder to communicate (our perspective) and to implement (their perspective).

2024-07-01 08:50 UTC, stanislaw commented
With the merge of https://github.com/strictdoc-project/strictdoc/pull/1903, basing on your PR here, I am now convinced that we should postpone moving the validation to `validate_requirement_field` and using the `FIELD_VALIDATORS`.

The current solution is quite nice in terms of the "at grammar time" parsing advantages, so let's keep it as-is until there is a stronger reason in the future to make a change. This comment effectively reverts my suggestion above that we should change your implementation to use `validate_requirement_field`.

We are all good with the current implementation for now. No change is needed.

> The only thing I can think of as disadvantage is that 3rd parties (e.g. language server, syntax highlighter, linter, ...) have a harder job reimplementing sdoc validation. They get for free what's written as TextX. The rules written in Python are harder to communicate (our perspective) and to implement (their perspective).

I agree in general. The only comment is that a more advanced use of LSP could actually build the traceability index to enable things like navigating nodes by clicking on their RELATIONS. In that case, only textX would not be enough.