WIP: Skip binaries in source tree rather than failing
strictdoc-project/strictdoc pull request #2033
Opened 2024-11-28 21:57 UTC by haxtibal

We're expecting source files to be UTF-8 text. Files that are invalid UTF-8 (most likely binary files) would have crashed StrictDoc. We can instead just skip them. Whatever they are, they are not traceable.

It's as simple as catching the `UnicodeDecodeError`. The majority of the diff is just about remembering whether a file was successfully read in `SourceFile.traceability_info` and refactorings resulting from it.

TODO:
- [ ] integration test would probably be good

2024-11-30 12:51 UTC, haxtibal commented on tests/integration/features/file_traceability/20_skip_invalid_utf8/test.itest
> +CHECK: info: Skip tracing binary file
There are 3 such lines expected, one for each invalid input file. I'd like to handle them more specific, but couldn't figure out yet how to use filecheck with either regex or directory substitution. Will try to figure out later - hints are also appreciated :)

2024-12-01 08:34 UTC, haxtibal commented on tests/integration/features/file_traceability/20_skip_invalid_utf8/test.itest
> +CHECK: info: Skip tracing binary file
Ignore, nothing particular here. Just a typo on my side.

2024-12-01 17:07 UTC, stanislaw requested changes
Hi @haxtibal, thanks for taking care of this issue.

I feel like the PR is doing a bit more than just addressing the runtime error thrown by the binary files.

I like the idea of connecting Source File with Source File Traceabiity Info but I think the relation between these classes should be from SFTI to SF, not the other way round like you did. I explain my reasoning in the comments.

I would be fine with either seeing a reduced PR that only addresses the reading of binary files or also a refactoring PR but then let's invert the relation order.

Note that in general, I am have been struggling with maintaining a growing number of entiries and relations between them using just Python dictionaries. Everything is fine with creating dictionaries but when their number grows, it becomes harder to manage what needs to be tracked together when things get added/deleted/updated.

What you see in the traceability index as a 'graph database' was my first attempt to bring some order into how things could be stored in an in-memory graph and all contributing links would be maintained with generalized one-to-one or one-to-many relations. I was planning of moving to this solution as an intermediate step for `file_traceability_index` as well or maybe even merging it to the traceability index by adding more of the enum type relations to the enum below. Your attempt to link the source file with a source file info is a step in a similar direction but it does not address this higher-level issue that my brain is lacking some additional order in how this code is maintained. Hopefully this longer speech explaining the bigger picture in my head, helps.


```
class GraphLinkType(IntEnum):
    MID_TO_NODE = 1
    UID_TO_NODE = 2
    UID_TO_REQUIREMENT_CONNECTIONS = 3
    NODE_TO_INCOMING_LINKS = 4
    DOCUMENT_TO_PARENT_DOCUMENTS = 5
    DOCUMENT_TO_CHILD_DOCUMENTS = 6
    DOCUMENT_TO_TAGS = 7
```

Thanks!

2024-12-02 20:57 UTC, haxtibal commented
> I like the idea of connecting Source File with Source File Traceabiity Info but I think the relation between these classes should be from SFTI to SF, not the other way round like you did. I explain my reasoning in the comments.

Ack. Should be doable as you lined it out here (thanks!). I first started the other way round because I found the existing but afaikt unused [SourceFile.traceability_info](https://github.com/strictdoc-project/strictdoc/blob/b59ab5f3829efcf61734f912af2f8b7fcef97e1a/strictdoc/core/finders/source_files_finder.py#L94) attribute and started using it without a look at object hierarchy, which would have made it clear.

>  or maybe even merging it to the traceability index by adding more of the enum type relations to the enum below

I'm afraid this could be a bit over my current time budget. Would you want me to do that? Otherwise I start with the less demanding SFTI -> SF approach.

2024-12-02 21:40 UTC, stanislaw commented
> > I like the idea of connecting Source File with Source File Traceabiity Info but I think the relation between these classes should be from SFTI to SF, not the other way round like you did. I explain my reasoning in the comments.
> 
> Ack. Should be doable as you lined it out here (thanks!). I first started the other way round because I found the existing but afaikt unused [SourceFile.traceability_info](https://github.com/strictdoc-project/strictdoc/blob/b59ab5f3829efcf61734f912af2f8b7fcef97e1a/strictdoc/core/finders/source_files_finder.py#L94) attribute and started using it without a look at object hierarchy, which would have made it clear.

No worries. These things can be not obvious at all, and we don't talk through them upfront. It sounds like you got the idea 👍 

> 
> > or maybe even merging it to the traceability index by adding more of the enum type relations to the enum below
> 
> I'm afraid this could be a bit over my current time budget. Would you want me to do that? Otherwise I start with the less demanding SFTI -> SF approach.

No worries, I just mentioned the "graph db" approach to give you some context. You don't have to do that. Please proceed with only the SFTI-SF approach.

P.S.

By the way, I was thinking of doing 'strictdoc office hours'. It looks like with Discord I can implement this idea using a public video/audio/screen channel where everyone can join. I am thinking of doing every Wednesday 17-19:00 CET time. By default, I will just work on something strictdoc* during this time, and if someone would join, we could simply chat freely about whatever comes up.

I will not start doing it this week because the work is a little demanding currently, but very likely starting from next one. I also need to spend some time to document the office hours in the docs and send some announcements to Discord and dozen of StrictDoc users who only use email.

2024-12-04 22:10 UTC, stanislaw commented on strictdoc/core/file_traceability_index.py
> +            source_file.traceability_info, SourceFileTraceabilityInfo
> assert isinstance(source_file.traceability_info, SourceFileTraceabilityInfo)

Yes, sorry. Scratch this particular line from the consideration but the general comment still applies. To be honest I have been and being very short on time due to some overtime at work, so doing everything StrictDoc* in a rush. Wish to come back to more quiet days.

2024-12-05 20:14 UTC, haxtibal commented on strictdoc/core/file_traceability_index.py
> +            source_file.traceability_info, SourceFileTraceabilityInfo
> the general comment still applies

Found and fixed one occurrence in the diff.

> I have been and being very short on time due to some overtime at work, so doing everything StrictDoc* in a rush. Wish to come back to more quiet days.

Please don't feel pushed by anything StrictDoc* and take quite days if possible. What you've already provided is awesome in its current state. This is not only my opinion, but feedback we get repeatedly from internal and external. It's way more then one could expect from a spare time project.

2024-12-23 12:16 UTC, stanislaw approved these changes
LGTM

Sorry for reviewing it much later. I had some extreme overtimes at work but now it is time to relax.

2024-12-23 12:16 UTC, merged