new feature INCLUDE_SECTION_FROM_FILE
strictdoc-project/strictdoc pull request #629
Opened 2022-03-21 21:02 UTC by BenGardiner

proposed in #604. This introduces the ability to include 'fragments' of strictdoc files. Dual-purposing `[SECTION]` as the include target _and_ a section-as-usual didn't seem possible in the grammar and `processor.py` structure so a `[FRAGMENT]` top-level directive for include files is proposed here.

2022-03-23 08:09 UTC, stanislaw requested changes
Thanks a lot for creating this PR. I believe that I have pushed it further to the right direction here: https://github.com/strictdoc-project/strictdoc/pull/632. I didn't know how I would open a MR back to your repository, so I simply opened another one here.

I suggest that you rebase your PR on top of the latest `main` branch, cherry-pick my code review commit and address all (relatively minor) comments. After that, the work should be mergeable.

The resolution of the fragments might need some attention though - it was a result of a quick work by me and the code there could surely be improved. Please check on your side if everything still works like you expect it to work.

2022-03-23 08:09 UTC, stanislaw commented on docs/sphinx/source/strictdoc.rst
> +Strictdoc ``.sdoc`` files can be built-up from including other fragment documents.
`StrictDoc`

2022-03-23 08:09 UTC, stanislaw commented on docs/sphinx/source/strictdoc.rst
> +The ``[INCLUDE_SECTION_FROM_FILE]`` element can be used anywhere a ``[SECTION]`` can
How about we call this `FRAGMENT_FROM_FILE`?

2022-03-23 08:09 UTC, stanislaw commented on docs/sphinx/source/strictdoc.rst
> +Include Files
`Include files` (the project follows European style for the capitalisation of headers)

2022-03-23 08:09 UTC, stanislaw commented on docs/sphinx/source/strictdoc.rst
> +    [FRAGMENT]
In the https://github.com/strictdoc-project/strictdoc/pull/632, I have tried to work around the `Dual-purposing [SECTION] as the include target and a section-as-usual` problem that you mentioned by making it explicit what's a fragment (`FRAGMENT`) and its contents (the usual `SECTIONS`).

So the example below should have:

```
[FRAGMENT]

[SECTION]
TITLE: Free text

[/SECTION]
```

2022-03-23 08:27 UTC, stanislaw commented on strictdoc/backend/sdoc/grammar/grammar.py
> +IncludeFromFile[noskipws]:
Let's call this `FragmentFromFile` and `[FRAGMENT_FROM_FILE]`.

2022-03-23 08:28 UTC, stanislaw commented on strictdoc/backend/sdoc/grammar/grammar.py
> +  ('UID: ' uid = /.+$/ '\n')?
Is there a use case for maintaining these three optional fields: `UID`, `LEVEL` and `TITLE`?

2022-03-23 13:52 UTC, BenGardiner commented
> Thanks a lot for creating this PR. I believe that I have pushed it further to the right direction here: #632. I didn't know how I would open a MR back to your repository, so I simply opened another one here.

Apologies for that extra work. I'm not sure if I could have prepared the PR differently to enable that. But happy to learn how.
 
> I suggest that you rebase your PR on top of the latest `main` branch, cherry-pick my code review commit and address all (relatively minor) comments. After that, the work should be mergeable.

No problem -- I can manage all the git backflips necessary

2022-03-25 17:38 UTC, BenGardiner commented
I've addressed all the review feedback here and in #632 .

2022-03-25 17:47 UTC, stanislaw approved these changes

2022-03-25 17:47 UTC, merged

2022-03-25 17:50 UTC, stanislaw commented
Thanks for doing all this work. I felt like I was almost reviewing my own code 😄 

Good catch with the before and after parts when extending the section_contents 👍 

Are you planning to push anything on top of this change or should I release a new Pip?

2022-03-25 17:56 UTC, BenGardiner commented
> Thanks for doing all this work. I felt like I was almost reviewing my own code 😄

It's my pleasure! Thank you and the team for the strictdoc project! 

> Are you planning to push anything on top of this change or should I release a new Pip?

Yes, _maybe_. Depending on discussion #630 ...